name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/setup@v3
        with:
          runtime: node@lts
          cache: true

      - name: Lint
        run: nr lint

      - name: Typecheck
        run: nr typecheck

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/setup@v3
        with:
          runtime: node@lts
          cache: true

      - name: Build
        run: nr build

      - name: Test
        run: nr test
